import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Every package whose code or data reaches `main.js`. `assertBundledPackages`
 * checks this list against the esbuild metafile, so a new dependency that ends
 * up in the bundle without a notice here fails the production build.
 *
 * `async` and `lodash` are dependencies of kuromoji but are not listed here:
 * the plugin imports `kuromoji/src/Tokenizer` and
 * `kuromoji/src/dict/DynamicDictionaries` directly, so kuromoji's
 * `DictionaryLoader` -- the only module requiring `async` -- is never reached.
 */
const APACHE_PACKAGES = [
  {
    id: "kuromoji",
    title: "Kuromoji.js",
    source: "https://github.com/takuyaa/kuromoji.js",
    // Reproduced from the headers of kuromoji's source files, which the
    // minifier strips.
    copyright: [
      "Copyright 2014 Takuya Asano",
      "Copyright 2010-2014 Atilika Inc. and contributors",
    ],
    licenseFile: "node_modules/kuromoji/LICENSE-2.0.txt",
    noticeFile: "node_modules/kuromoji/NOTICE.md",
  },
];

const MIT_PACKAGES = [
  {
    id: "wink-nlp",
    source: "https://github.com/winkjs/wink-nlp",
    licenseFile: "node_modules/wink-nlp/LICENSE",
  },
  {
    id: "wink-eng-lite-web-model",
    source: "https://github.com/winkjs/wink-eng-lite-web-model",
    licenseFile: "node_modules/wink-eng-lite-web-model/LICENSE",
  },
  {
    id: "pluralize",
    source: "https://github.com/blakeembrey/pluralize",
    licenseFile: "node_modules/pluralize/LICENSE",
  },
  {
    id: "doublearray",
    source: "https://github.com/takuyaa/doublearray",
    licenseFile: "node_modules/doublearray/LICENSE.txt",
  },
  {
    id: "zlibjs",
    source: "https://github.com/imaya/zlib.js",
    licenseFile: "node_modules/zlibjs/LICENSE",
  },
];

const DECLARED_PACKAGES = new Set(
  [...APACHE_PACKAGES, ...MIT_PACKAGES].map((pkg) => pkg.id),
);

function readText(relativePath) {
  const absolute = path.join(root, relativePath);
  if (!fs.existsSync(absolute)) {
    throw new Error(
      `missing license file: ${relativePath} (run \`npm ci\` before building)`,
    );
  }
  return fs.readFileSync(absolute, "utf8");
}

/**
 * zlibjs ships its license as a JavaScript block comment. Strip the comment
 * syntax so the text can be embedded in one without terminating it early.
 */
function unwrapBlockComment(text) {
  if (!text.trimStart().startsWith("/*")) {
    return text;
  }
  return text
    .replace(/^\s*\/\*+[^\n]*\n/, "")
    .replace(/\n[^\n]*\*\/\s*$/, "")
    .split("\n")
    .map((line) => line.replace(/^\s*\*\x20?/, ""))
    .join("\n");
}

/** kuromoji's NOTICE.md ends with two stray non-ASCII characters. */
function stripTrailingJunk(text) {
  return text.replace(/[^\x20-\x7e\n]+\s*$/, "").trimEnd();
}

function licenseText(relativePath) {
  return stripTrailingJunk(unwrapBlockComment(readText(relativePath)));
}

function apacheSection(pkg) {
  return [
    `## ${pkg.title}`,
    "",
    ...pkg.copyright,
    "",
    `Source: <${pkg.source}>`,
    "",
    "This copy has been modified: its modules were bundled into `main.js` and",
    "minified, and the IPADIC dictionary files (`dict/*.dat.gz`) were embedded",
    "as binary payloads.",
    "",
    "### Apache License 2.0",
    "",
    licenseText(pkg.licenseFile),
    "",
    `### NOTICE, reproduced verbatim from ${pkg.title}`,
    "",
    licenseText(pkg.noticeFile),
  ].join("\n");
}

function mitSection(pkg) {
  return [
    `### ${pkg.id}`,
    "",
    `Source: <${pkg.source}>`,
    "",
    licenseText(pkg.licenseFile),
  ].join("\n");
}

export function buildNotices() {
  const notices = [
    "# Third-party notices",
    "",
    "`main.js` is a single file produced by bundling and minifying this plugin's",
    "own source together with the third-party components listed below. That",
    "transformation removes the comment headers carried by the original sources,",
    "so their copyright and license notices are reproduced here in full.",
    "",
    "This file is generated by `scripts/licenses.mjs` on every build and any",
    "edit made here is overwritten. Change that script instead.",
    "",
    "## Suggested Notes",
    "",
    licenseText("LICENSE"),
    "",
    ...APACHE_PACKAGES.map(apacheSection),
    "",
    "## MIT-licensed components",
    "",
    ...MIT_PACKAGES.map(mitSection),
  ].join("\n");

  if (notices.includes("*/")) {
    throw new Error("notices contain `*/` and cannot be embedded in a banner");
  }
  return notices;
}

export function bannerFrom(notices) {
  return `/*!\n${notices}\n*/`;
}

/**
 * Fail the build when the bundle pulls in a package that has no notice, or
 * when a declared package is no longer bundled and its notice is now stale.
 */
export function assertBundledPackages(metafile) {
  const bundled = new Set();
  const marker = "node_modules/";
  for (const input of Object.keys(metafile.inputs)) {
    // Match the last marker so a nested install -- for example
    // node_modules/kuromoji/node_modules/zlibjs/... -- reports zlibjs rather
    // than the package it was nested under.
    const at = input.lastIndexOf(marker);
    if (at < 0) {
      continue;
    }
    const match = input
      .slice(at + marker.length)
      .match(/^((?:@[^/]+\/)?[^/]+)/);
    if (match) {
      bundled.add(match[1]);
    }
  }

  const undeclared = [...bundled].filter((id) => !DECLARED_PACKAGES.has(id));
  const unused = [...DECLARED_PACKAGES].filter((id) => !bundled.has(id));
  if (undeclared.length === 0 && unused.length === 0) {
    return;
  }

  const problems = [];
  if (undeclared.length > 0) {
    problems.push(`bundled without a notice: ${undeclared.sort().join(", ")}`);
  }
  if (unused.length > 0) {
    problems.push(`declared but not bundled: ${unused.sort().join(", ")}`);
  }
  throw new Error(
    `third-party notices are out of date in scripts/licenses.mjs\n  ${problems.join("\n  ")}`,
  );
}
